### PR TITLE
Update dwarf planets, centaurs, TNOs

### LINKED ISSUE #8: textures and models missing
data/solar-system/dwarf-planets/dwarf-planets.ssc
The Ceres textures and models missing.

Should this dwarf planet removed from celestia, as one of them can be downloaded from celestiamotherlode.
http://www.celestiamotherlode.net/catalog/show_addon_details.php?addon_id=1651

### PR DESCRIPTION
**Pull request by SevenSpheres**
Data, models, and textures updated and several new objects added, with **pedro_jg** as co-author for the outersys.ssc update. Ceres' texture in Project Echoes has "gaps improved by Oleg-Pluton" making the license ambiguous, so I've tried to fill the gaps in the [original texture](https://www.deviantart.com/fargetanik/art/Ceres-Albedo-Texture-Map-21k-684083396) myself.

Askaniy's Charon texture (which I already added in a previous PR) is derived from FGN's texture, which is derived from the one on [Steve Albers' site](https://stevealbers.net/albers/sos/sos.html), which as mentioned in #53 doesn't seem to be licensed appropriately for use in Celestia. However, the texture looks pretty much the same as public domain textures like [this](https://astrogeology.usgs.gov/search/map/Charon/NewHorizons/Charon_NewHorizons_Global_Mosaic_300m_Jul2017) or [this](https://commons.wikimedia.org/wiki/File:Charon_map_iau1803c.jpg), and I'm not sure what part of it is from Albers' texture. I have contacted Albers about this though.

New objects:
* Gonggong, a probable dwarf planet
* Other large TNOs: Chaos, Huya, Salacia, Varda, Gǃkúnǁʼhòmdímà, Dziewanna
* Chariklo, a ringed centaur
* Albion, the first TNO discovered (after Pluto)
* Lempo, a 3-body TNO system
* Arrokoth, which was visited by the New Horizons spacecraft

Closes #8.

### CODE REVIEW

**Review by Askaniy — APPROVED** [review]

**Review by 375gnu — APPROVED** [review]

**Comment by SevenSpheres** [comment]
> Askaniy's Charon texture (which I already added in a previous PR) is derived from FGN's texture, which is derived from the one on [Steve Albers' site](https://stevealbers.net/albers/sos/sos.html), which as mentioned in #53 doesn't seem to be licensed appropriately for use in Celestia. However, the texture looks pretty much the same as public domain textures like [this](https://astrogeology.usgs.gov/search/map/Charon/NewHorizons/Charon_NewHorizons_Global_Mosaic_300m_Jul2017) or [this](https://commons.wikimedia.org/wiki/File:Charon_map_iau1803c.jpg), and I'm not sure what part of it is from Albers' texture. I have contacted Albers about this though.

Finally got a reply about this.
stevealbers

**Comment by 375gnu** [comment]
@SevenSpheres could you clarify with him question what exact license this texture can be used?

**Comment by SevenSpheres** [comment]
stevealbers2

**Comment by 375gnu** [comment]
So, let's say he approved CC-SA-NC for the original map and CC-SA for derived work.

**Pull request merged**
