### PR TITLE
Update content [WIP]

### PR DESCRIPTION
**Pull request by SevenSpheres**
Making the branch I've been working on into a pull request - WIP, still a *lot* that needs to be done...

### CODE REVIEW

**Comment by eyvallah** [comment]
Just noticed the last commit, I think you should keep the order the file alphabetical by moving Hong Kong a bit up

**Comment by SevenSpheres** [comment]
Yeah the commit history is a mess right now...

**Comment by LukeCEL** [comment]
The Hong Kong thing isn't the only thing that's wrong with world-capitals.ssc right now. It needs a complete overhaul. Perhaps that could be done for 1.7.0, maybe we have enough time to do that right now, who knows.

Right now the missing changes are:
- Palau's capital is now Ngerulmud, not Koror
- Myanmar's capital is now Naypyidaw, not Rangoon (Yangon)
- Podgorica, Montenegro
- Priština, Kosovo (partially recognized)
- Juba, South Sudan
- Georgia might have a new (legislative) capital: Kutaisi? More research needed.
- Burundi's capital is now Gitega, not Bujumbura
- Kazakhstan's capital Astana renamed to Nur-Sultan

**Comment by LukeCEL** [comment]
> Yeah the commit history is a mess right now...

Don't worry about the commit history right now, you can just rebase everything at the end.

**Comment by 375gnu** [comment]
On 5/24/20, LukeCEL <notifications@github.com> wrote:

> - Georgia might have a new (legislative) capital: Kutaisi? More research
> needed.

No. It's still Tbilisi.

**Comment by SevenSpheres** [comment]
> Kazakhstan's capital Astana renamed to Nur-Sultan

Fixed that, the rest need more than name changes and can wait for 1.7.0

**Comment by LukeCEL** [comment]
I just realized that if you change any of the world capitals' names, you also have to edit the .po files.

**Comment by 375gnu** [comment]
> I just realized that if you change any of the world capitals' names, you also have to edit the .po files.

this can be done later

**Comment by SevenSpheres** [comment]
Finally getting back to this; somehow the PR closed itself while I was rebasing...

**Comment by SevenSpheres** [comment]
Just to note the current status of this PR... @pedro-fixingstuff (pedro_jg) is working on completing the data file updates. I'm still not sure what textures to use for most objects so I've been copying them all from Project Echoes.

**Pull request closed without merging**
