### PR TITLE
Complete update of exoplanet catalogue

### PR DESCRIPTION
**Pull request by SevenSpheres**
Author: TTarrants/Sirius_Alpha

Some changes still need to be made, but I don't think these prevent inclusion in the repository:
* Redundant HD names removed
* Proper names listed first
* Albedo parameters updated

### CODE REVIEW

**Review by Askaniy — APPROVED** [review]

**Comment by SevenSpheres** [comment]
> * Redundant HD names removed
> * Proper names listed first

These have been done now.

**Comment by SevenSpheres** [comment]
apparently updating the albedo parameters will be easy to do, so expect another force-push

**Comment by SevenSpheres** [comment]
Albedo parameters updated and a few more planetary-mass/transiting brown dwarfs added, should be ready now

**Review by 375gnu — APPROVED** [review]

**Review by 375gnu — CHANGES_REQUESTED** [review]
del

**Review by 375gnu — APPROVED** [review]

**Review by ajtribick — APPROVED** [review]

**Review by levinli303 — APPROVED** [review]

**Comment by SevenSpheres** [comment]
There's an issue with VB 10 being duplicated, so I'm going to have to make another commit

**Pull request merged**
