### PR TITLE
Update Tethys, Dione and Enceladus textures from JPL images

### PR DESCRIPTION
**Pull request by mattiaverga**
Current Tethys and Enceladus textures are really too washed out, not sure if that is wanted or not... I therefore updated them with color maps from JPL (which I think are the same as the previous, but retaining colors).

I've also saved the textures in AVIF format, as Celestia 1.7 seems to handle it well, which makes a small save in file sizes. Otherwise we can also double the resolution while retaining the same size, if you prefer.

I only modified those two for now, if that's ok I can work on other textures.

### CODE REVIEW

**Comment by SevenSpheres** [comment]
These are enhanced color maps, and comparing them to the existing maps shows they're incorrectly offset. In default Celestia we try to use true colors. I also see that Tethys' normal map was removed, without modifying solarsys.ssc which still refers to it.

To clarify the license issue with the FarGetaNik textures - he gave permission for use in Celestia in 2021, but the textures were originally released under a non-commercial license and he's refused to explicitly state a new license for use in default Celestia. If we're following strict licensing requirements so that simply giving permission isn't enough, these would have to be replaced, but presumably someone could create equivalent textures from the same public domain sources?

**Comment by mattiaverga** [comment]
Thanks. I've found the true colors maps on JPL site and updated textures. I've also corrected solarsys.ssc.

**Comment by SevenSpheres** [comment]
Well, these textures at least align with the current ones and aren't in enhanced color, but they're older and not exactly true color (they're grayscale and darker than true-albedo textures would be). I would really prefer to not downgrade and remove textures, but I guess if it's necessary under the stricter licensing requirements...

**Comment by mattiaverga** [comment]
I've been struggling for hours trying to make sense of the Gaskell's models data available in vertex-facet format and in Implicitly Connected Quadrilateral (ICQ) format to enhance the texture maps, but I cannot manage to do so. I think I'll retire this PR.

Just a final question: in the end of my searches I found that NASA makes available complete 3D models in an open standard glTF format. For example, Tethys model is [here](https://science.nasa.gov/resource/tethys-3d-model/) and [here](https://science.nasa.gov/saturn/moons/tethys/) is a working example. Do you think such models can be useful to be imported in Celestia, so that we can avoid the texture/normal maps? Should I open a feature request in the main Celestia repository?

**Comment by SevenSpheres** [comment]
This was discussed on Discord and John Van Vliet has created higher-resolution Tethys and Dione normal maps from the Gaskell models. After confirming the license I can make a pull request to add these.

**Comment by mattiaverga** [comment]
So, should I rework the images in this PR to be JPEG? Or do you prefer not to change current textures?

**Comment by SevenSpheres** [comment]
Disregarding color, it would be better to use the enhanced color maps over the grayscale maps because they're newer and more accurate. It should be possible to recolor them to approximate true color (as FarGetaNik did).

**Comment by mattiaverga** [comment]
Fair enough.
Although I'm not a scientist, do note that those color maps are made from IR + Visual + UV data, so I doubt it's just a matter of "recoloring" them to have a real true color texture. Someone will have to work them out from raw data.

**Pull request closed without merging**
