### PR TITLE
Revision 3 of the CMOD model for the default ISS

### PR DESCRIPTION
**Pull request by DaveBowman2001**
Solar Arrays rotated 90 degrees perpendicular to the station's main body. Replaces the current CMOD model (Revision 2) first introduced in PR #91
image
_Sample screenshot_

### CODE REVIEW

**Comment by DaveBowman2001** [comment]
> Do you know what the license/copyright is for this model, so we can create the .license file?

Here's the note left by Andrew Farnaby, the original author, from the defunct Project Alpha site
IMG_20240904_073931

...and we have this written on its SSC file (as of 2022-Nov-5):
IMG_20240904_074117

**Comment by ajtribick** [comment]
Ok so I think that helps cover the copyright side of things. Licensing seems a bit more problematic - according to that description it looks like it's ok to use in Orbiter, but we aren't Orbiter.

As I see it, the options are:

* Contact Andrew Farnaby / Bob Hundley and confirm what license we could use their work under
* Start from scratch
* Remove the ISS add-on from the Celestia distribution

**Comment by DaveBowman2001** [comment]
I was wondering when did Andrew Farnaby's *ProjectAlpha* ISS became a part of Celestia's default installation. Before I made my changes with #91 and #201, a variant of it from the [Motherlode](http://www.celestiamotherlode.net/addon/addon_1199.html) was the default one for more than a decade afaik as evident from this [SSC intro](https://github.com/CelestiaProject/CelestiaContent/pull/71/files#diff-01159351cda7aa4b0bc8084c2535ea63774ff1673a2f976151a02827769aa3be):
IMG_20240905_163644
satellites_ISS_June_2008_1__krisci3

**Comment by DaveBowman2001** [comment]
> As I see it, the options are:
> 
> * Contact Andrew Farnaby and Bob Hundley and confirm what license we could use their work under

I wish I knew what their present-day profiles are directly. As for Bob Hundley, I am not quite certain if he is [bh](https://celestiaproject.space/forum/memberlist.php?mode=viewprofile&u=511) on the Celestia Forums (he did say he was one of the authors of some old Shuttle models for NASA which became the basis of my own shuttle addon, hence my indirect clue of his identity)

**Comment by DaveBowman2001** [comment]
@ajtribick here's our previous [Discord](https://discord.com/channels/558624707147071489/691413425494032474/1031735002330824704) conversation with @SevenSpheres and @pedro-fixingstuff last year, regarding the licensing for the default ISS when I made my previous modification on #91:
> Me: "_Regarding the default ISS model from <#558643969307967504> and <#621252660976418817>, here's the status of the modified Alpha model that will replace the stock model. There's still a lot of work to do, as some modules that were launched are in wrong positions (like Tranquility and Cupola)_"
> unknown
> 
> 7Sph: "_Where is this model from? Do you know anything about the licensing?_"
> 
> Me: "_[Stage 13](http://www.celestiamotherlode.net/addon/addon_293.html). For context, here's the ISS addon that became the stock model from 1.6.0 above ([krisci3](http://www.celestiamotherlode.net/addon/addon_1199.html))_"
> 
> Pedro_JG: "_[Bob Hundley](http://web.archive.org/web/20080708183038/http://www.bobhundley.com/celestia/iss.html) tells us the model is originally from [Andrew Farnaby](http://web.archive.org/web/20051231223046/http://www.f-a-d.co.uk/)_"
> 
> 7Sph: "_Yes, it looks like both the Space Station Alpha model and the default ISS model are derived from the same model by Andrew Farnaby. I guess that means we can assume **CC BY-SA** compatible licensing?_"
> 
> Me: "_Well, technically yes_"
> 
> 7Sph: "_If you're making modifications to the model anyway, why not start with the default 2008 model instead of an older one?_"
> 
> Me: "_The original model is obviously more complete than the 2008 model, and it's much easier to work with as I'll just remove the cancelled modules and relocate some of them_"

**Comment by SevenSpheres** [comment]
I think at that point I was assuming that the default ISS model was under a suitable license, which now seems uncertain.

**Review by ajtribick — CHANGES_REQUESTED** [review]
So summarising the state of the discussions, I think that without licensing confirmation we cannot continue to use the Orbiter Project Alpha model or its derivatives - and so far I haven't seen any way to contact the original author Andrew Farnaby. I'm therefore suggesting removal of the ISS add-on (https://github.com/CelestiaProject/CelestiaContent/pull/202) as the immediate fix for the licensing issue.

**Comment by ajtribick** [comment]
As mentioned on #202 it doesn't seem anyone's aware of a usable license for the original model from which this is derived, so I'm going to close this for now. If more information comes up in the future, I would have no problems with re-adding.

**Pull request closed without merging**
