### PR TITLE
Update stars

### PR DESCRIPTION
**Pull request by SevenSpheres**
- Update star names
- Remove stars from stc files that are already in stars.dat
- Add some oblate stars to revised.stc
- Some fixes in nearstars.stc and visualbins.stc

(co-author: @LukeCEL)

This shouldn't be merged yet, it's anticipating #18 being merged. @LukeCEL should also make a PR for jsdc.stc (I could do it but he made the file...)

This PR also makes #15 redundant.

### CODE REVIEW

**Comment by LukeCEL** [comment]
I looked through starnames.dat for anything missing regarding variable star designations. Here's what I found.

_Designations that should be added:_
10679 = DK Tri
10680 = DL Tri
8751 = ETA1 Hyi
19255 = V491 Per (binary)

_Designations in the GCVS that are not in SIMBAD. These are the SIMBAD's mistake, but I think we could hold off on these until SIMBAD corrects them. At some point in the future I will email them about this._
39453 = FX CMi
13494 = LU Cet
30807 = V441 CMa
38144 = V514 Gem
41322 = V751 Pup
11397 = V807 And
93954 = V875 Lyr (binary)
88887 = V3714 Oph

_Incorrect cross-identification with HIP star in GCVS:_
99085 = RY Cap

_to be avoided (for now), because of the MU/NU ambiguity:_
1263 = MU Cas
35355 = MU CMa
81554 = MU TrA
69403 = MU Vir
72825 = NU Aps
111726 = NU Aqr
26258 = NU Ori
98608 = NU Pav
105958 = NU Peg
53209 = NU UMa
71455 = NU Vir

_to be avoided (for now), because of capital/lowercase ambiguity:_
46806 = R Car
69754 = R Cen
37415 = R Pup
49477 = R Vel
49751 = S Car
82516 = S Her
88923 = T Her
38074 = T Pup
20390 = T Tau
42321 = T Vel
53589 = U Car
61286 = U Cen
80488 = U Her
71116 = V Cen
19004 = V Eri
58107 = W Cen
37893 = W Pup
50230 = W Vel
41793 = X Car
78574 = X Her
36685 = X Pup
48662 = X Vel
70969 = Y Cen
9767 = Y Eri
81354 = Y Her
46502 = Y Vel
87965 = Z Her
36669 = Z Pup

_Designations that do not need to be added, because they are in nearstars.stc:_
30920 = V577 Mon
82817 = V1054 Oph

_Designations that I should add in nearstars.stc:_
88601 = V2391 Oph

_Miscellaneous errors:_
79551 = SIG CrB C:17 CrB C

**Comment by SevenSpheres** [comment]
Update:
- added designations listed by @LukeCEL (including those that cause capital/lowercase ambiguity, since the old nearstars.stc had similar designations, e.g. A Cen and a Cen)
- fixed 64 Eri and SIG CrB
- added GAM Aur designation for Elnath
- the designation V2391 Oph is missing from nearstars.stc and should be added (I didn't add it though)

**Comment by LukeCEL** [comment]
Here are some Bayer/Flamsteed designations that need to be modified or added:

SINGLE BAYER/FLAMSTEED DESIGNATIONS: Be warned that for some of these designations, the constellations don't correspond to their actual locations, because of proper motion or constellation border changes. However, I think they should still be included because the 1.6.1 starnames.dat included 6 Per (which is in Andromeda). For these, probably just best to add them to the end and sort everything.

103681 = 10 Aqr
106942 = 24 Aqr
109369 = 36 Aqr
109460 = 37 Aqr
109720 = 40 Aqr
110786 = 54 Aqr
111539 = 61 Aqr
111843 = 64 Aqr
112161 = 65 Aqr
112813 = 72 Aqr
113085 = 75 Aqr
103640 = 8 Aqr
114006 = 84 Aqr
114054 = 85 Aqr
114164 = 87 Aqr
103728 = 9 Aqr
10810 = 23 Ari
11427 = 25 Ari
13579 = 44 Ari
14021 = 50 Ari
14150 = 51 Ari
27458 = 28 Aur
26426 = 20 Cam
26700 = 21 Cam
26587 = 22 Cam
27283 = 28 Cam
29315 = 38 Cam
29348 = 39 Cam
31944 = 41 Cam
40215 = 55 Cam
101751 = 13 Cap
103703 = 21 Cap
104429 = 26 Cap
106568 = 38 Cap
107527 = 50 Cap
44599 = G Car
50847 = L Car
31407 = N Car
9802 = 51 Cas
10031 = 54 Cas
71865 = b Cen
108925 = 15 Cep
2343 = 11 Cet
2994 = 15 Cet
5315 = 29 Cet
5646 = 35 Cet
5666 = 36 Cet
635 = 4 Cet
5985 = 40 Cet
6048 = 41 Cet
9165 = 58 Cet
10033 = 62 Cet
39888 = 11 Cnc
40007 = 13 Cnc
42578 = 42 Cnc
42791 = 44 Cnc
43463 = 52 Cnc
44336 = 68 Cnc
39447 = 7 Cnc
44637 = 71 Cnc
44918 = 78 Cnc
45153 = 80 Cnc
45699 = 83 Cnc
58661 = 1 Com
60123 = 10 Com
62819 = 33 Com
54742 = PSI Crt
64244 = 16 CVn
64355 = 18 CVn
100565 = 72 Dra
107230 = 78 Dra
103813 = 2 Equ
18122 = 29 Eri
21515 = 49 Eri
30003 = 10 Gem
30588 = 14 Gem
30757 = 15 Gem
37636 = 192 Gem
28969 = 2 Gem
31158 = 20 Gem
31368 = 22 Gem
31525 = 23 Gem
29288 = 4 Gem
36739 = 67 Gem
38495 = 84 Gem
32968 = 87 Gem
79608 = 12 Her
79634 = 13 Her
79704 = 15 Her
79724 = 17 Her
79846 = 18 Her
79889 = 19 Her
80648 = 26 Her
80927 = 31 Her
81066 = 32 Her
81717 = 38 Her
81991 = 41 Her
82000 = 46 Her
82324 = 48 Her
83876 = 62 Her
45588 = 25 Hya
51614 = 43 Hya
47266 = 11 Leo
47382 = 12 Leo
48298 = 21 Leo
48881 = 26 Leo
49850 = 33 Leo
52120 = 50 Leo
53460 = 57 Leo
54515 = 66 Leo
55533 = 71 Leo
55769 = 82 Leo
47247 = 9 Leo
72702 = 10 Lib
73953 = 22 Lib
71652 = 3 Lib
75294 = 30 Lib
48256 = 16 LMi
48428 = 17 LMi
50857 = 26 LMi
51047 = 29 LMi
52240 = 39 LMi
53195 = 45 LMi
54196 = 51 LMi
31763 = 10 Lyn
34572 = 17 Lyn
30278 = 3 Lyn
31526 = 9 Lyn
34904 = 23 Mon
30700 = 9 Mon
65522 = 67 Mus
82007 = 15 Oph
85242 = 191 Oph
82758 = 22 Oph
83508 = 28 Oph
83566 = 31 Oph
84605 = 38 Oph
85365 = 47 Oph
85703 = 50 Oph
85979 = 54 Oph
86041 = 56 Oph
116972 = 76 Peg
117735 = 83 Peg
30932 = 61 Pic
108571 = 11 PsA
112362 = 20 PsA
7364 = 100 Psc
7709 = 103 Psc
7710 = 104 Psc
115945 = 11 Psc
115951 = 12 Psc
116422 = 15 Psc
1340 = 37 Psc
1392 = 38 Psc
1427 = 39 Psc
1595 = 40 Psc
1948 = 43 Psc
2025 = 45 Psc
2213 = 46 Psc
2415 = 49 Psc
4832 = 70 Psc
5175 = 76 Psc
6527 = 92 Psc
6815 = 95 Psc
37379 = 140 Pup
38146 = 188 Pup
38901 = CHI Pup
34339 = D Pup
37223 = e Pup
35347 = M Pup
36817 = n Pup
36917 = p Pup
37043 = y2 Pup
81304 = H Sco
80911 = N Sco
86170 = Q Sco
73193 = 1 Ser
77249 = 29 Ser
79047 = 46 Ser
79492 = 49 Ser
49739 = 16 Sex
50100 = 20 Sex
50140 = 21 Sex
51117 = 26 Sex
51135 = 27 Sex
48087 = 3 Sex
51451 = 31 Sex
51592 = 32 Sex
52401 = 34 Sex
52884 = 39 Sex
48286 = 5 Sex
48552 = 9 Sex
98754 = 14 Sge
95435 = 3 Sge
89567 = 17 Sgr
90713 = 23 Sgr
92602 = 31 Sgr
95486 = 48 Sgr
88142 = 5 Sgr
23214 = 101 Tau
23949 = 107 Tau
26925 = 127 Tau
27106 = 128 Tau
28455 = 140 Tau
17832 = 26 Tau
7948 = 1 Tri
2578 = BET3 Tuc
45812 = 20 UMa
46239 = 21 UMa
52650 = 40 UMa
60712 = 72 UMa
73808 = 10 UMi
74806 = 12 UMi
75152 = 14 UMi
77942 = 17 UMi
76695 = 18 UMi
72181 = 6 UMi
73440 = 9 UMi
70220 = 103 Vir
60088 = 14 Vir
61969 = 28 Vir
64625 = 56 Vir
65074 = 62 Vir
66131 = 77 Vir
66465 = 81 Vir
67355 = 88 Vir
68888 = 94 Vir
105411 = 34 Vul

BINARY BAYER/FLAMSTEED DESIGNATIONS: these include companion stars, and some
pairs that are wide enough that they were resolved as individual stars in the Hipparcos catalogue. For "B" stars, the other star should also be renamed as "A".

111546 = 8 Lac A
111544 = 8 Lac B
35731 = 20 Lyn A
35726 = 20 Lyn B
92118 = 5 Aql B - rename 92117 to 5 Aql A
115125 = 94 Aqr B - rename 115126 to 94 Aqr A
10303 = 66 Cet B - rename 10305 to 66 Cet A
60891 = 17 Com B - rename 60904 to 17 Com A
59827 = 2 CVn B - rename 59831 to 2 CVn A
99676 = 31 Cyg B - rename 99675 to 31 Cyg A
31156 = 20 Gem B - rename 31158 to 20 Gem A
1197 = 35 Psc B - rename 1196 to 35 Psc A

COMMON PROPER MOTION PAIRS WITH A BAYER/FLAMSTEED STAR: these could also
be added. You should check the hierarchy for these in closer detail.

24502 = 14 Aur C
103571 = EPS Equ C
80474 = RHO Oph C
80461 = RHO Oph D
26551 = SIG Ori D

MORE MISSING BAYER/FLAMSTEED DESIGNATIONS: these already have an entry in starnames.dat so they should just be appended (before the variable star designation).

92501 (V1728 Aql) = 7 Aql
105019 (IW Aqr) = 14 Aqr
44626 (V345 Car) = E Car
21479 (R Dor) = P Dor
112355 (CG Oct) = B Oct
37345 (V468 Pup) = d4 Pup
37174 (MY Pup) = y3 Pup
21082 (V1146 Tau) = 84 Tau

GOULD DESIGNATIONS: most Gould designations aren't used at all. However, a few of them have snuck onto SIMBAD, and some were even in the original starnames.dat. Therefore, I think any Gould designations that is on SIMBAD should also be in starnames.dat.

48589 (QX Car) = 163 Car
54360 (V815 Cen) = 46 Cen
42794 (RS Cha) = 9 Cha
72773 (AX Cir) = 26 Cir
26368 (AZ Dor) = 29 Dor
56862 (GT Mus) = 12 Mus
19917 (TT Ret) = 286 Ret
89276 (AP Sgr) = 12 Sgr
89980 (V4028 Sgr) = 70 Sgr

MISCELLANEOUS CASES: some of these may or may not be errors. In any case, they should be carefully researched.

5144/5141 - 77 Psc A and B are switched in starnames.dat relative to SIMBAD. I am not sure which is correct.
8486 - EZ Cet could possibly take the Bayer designation CHI Cet B.
37297 - is listed as n1 Pup in starnames.dat but SIMBAD says it is d1 Pup.
35363 - is listed as NV Pup in starnames.dat but SIMBAD says it is ups1 Pup.

**Comment by SevenSpheres** [comment]
Fixed most of the things mentioned by @LukeCEL, should be ready to merge now (after #18 is merged of course)

**Pull request merged**
