### PR TITLE
Updated mass for Pluto-Charon

### PR DESCRIPTION
**Pull request by JiliTheSpaceboy**
From https://ui.adsabs.harvard.edu/abs/2024AJ....167..256B/abstract Mars's mass is changed by a minuscule amount; previously I assumed that the GM given is total system mass, but I couldn't find support to this claim.

### CODE REVIEW

**Review by SevenSpheres — APPROVED** [review]

**Comment by JiliTheSpaceboy** [comment]
Apologies for an update to this pull request after approval; I figured I would like to update before I forget about it. The update is fixing the rings of Quaoar.

**Comment by 375gnu** [comment]
@JiliTheSpaceboy could you post comparison of Quaoar with old and new rings?

**Comment by JiliTheSpaceboy** [comment]
(The new commit changes the outer edge of the rings of Quaoar by 4 km)

> @JiliTheSpaceboy could you post comparison of Quaoar with old and new rings?

The rings appear to be imperceptible in the program itself because it's extremely tenuous. You can see the difference if you download the ring files and see what is encoded within each pixel. I'd hoped that viewing the rings from a more oblique angle would help bring them up, but no such luck.

**Comment by 375gnu** [comment]
Could you provide license information for the image?

**Comment by JiliTheSpaceboy** [comment]
> Could you provide license information for the image?

Do you mean quaoar-rings.png? That one is covered by textures/medres/quaoar-rings.png.license

**Comment by 375gnu** [comment]
What's the source of the new file?

**Comment by JiliTheSpaceboy** [comment]
> What's the source of the new file?

I made the quaoar-rings.png myself. It's based on https://ui.adsabs.harvard.edu/abs/2024A%26A...683C...4P/abstract .

**Pull request merged**
