### PR TITLE
Total locations update. Adds Ceres, fixes Puck

### PR DESCRIPTION
**Pull request by Askaniy**

### CODE REVIEW

**Comment by SevenSpheres** [comment]
I would prefer the headers to be as they were - "the Moon" instead of "Moon", and for the moons of the giant planets "the moons of [planet]" instead of listing all of them, since the sub-headers are there.

**Comment by Askaniy** [comment]
I deliberately left it as is. Argumentation: the fact that these are the satellites of a planet is already known from the file name. But if you need to find out for which satellites there are locations, you will have to scroll through thousands of lines (or flip through the search results). It's less convenient.

I can hardcode "the" for Moon as an exception. And if you really want it, this can be a compromise (example)
`# 707 locations on the moons of Jupiter: Amalthea, Thebe, Io, Europa, Ganymede and Callisto.`

**Comment by SevenSpheres** [comment]
Please at least use "the Moon", that's how it's referred to in English.

**Review by SevenSpheres — APPROVED** [review]
you should probably squash the commits into one

**Pull request merged**
