### PR TITLE
2024-01-21 General data update

### PR DESCRIPTION
**Pull request by JiliTheSpaceboy**
- Updated rings of dwarf planets and centaurs wherever data allows; Chiron's rings are currently hidden due to not enough data being available
- Updated Orcus' colors
- Corrected Vanth's radius
- Added mass for Himalia
- Updated Chariklo's dimensions
- Updated masses for Saturn and Neptune
- Updated ring textures for Haumea, Quaoar (corrected opacity), and Chariklo.

Current issues:
- Licensing of haumea-rings, as the version with fictional details has been replaced; the current license file has not yet been changed.
- The ring textures are 2 pixels tall, as for whatever reason paint.net doesn't allow me to make them 1 pixel tall.

### CODE REVIEW

**Comment by JiliTheSpaceboy** [comment]
As unlikely as it is, please do not merge this pull request before Askaniy comments on the Haumea ring texture update.

**Comment by Askaniy** [comment]
I don't mind replacing my texture with a detailless one.
Noticed that the height is 2 pixels, not 1, which is a little strange.

**Comment by JiliTheSpaceboy** [comment]
> I don't mind replacing my texture with a detailless one.
> Noticed that the height is 2 pixels, not 1, which is a little strange.

Thanks
paint.net doesn't allow me to scale these files down to 1 pixel unfortunately; would appreciate help on this one.

**Comment by SevenSpheres** [comment]
You can just edit the license file to
```
SPDX-FileCopyrightText: 2024 AstroChara

SPDX-License-Identifier: (CC0-1.0|CC-BY-4.0|CC-BY-SA-4.0)

```
The other ring textures will need license files too.

Try using another program like GIMP to scale the textures.

**Comment by JiliTheSpaceboy** [comment]
> You can just edit the license file to
> 
> ```
> SPDX-FileCopyrightText: 2024 AstroChara
> 
> SPDX-License-Identifier: (CC0-1.0|CC-BY-4.0|CC-BY-SA-4.0)
> ```
> 
> The other ring textures will need license files too.
> 
> Try using another program like GIMP to scale the textures.

Done.

GIMP is godawful at transparency it's not even funny. That said I realized I could just crop the ring texture so I am going to update the textures now.

**Review by SevenSpheres — APPROVED** [review]
approving, though eventually Chiron will need a ring texture (or Chariklo's restored as a placeholder)

**Comment by JiliTheSpaceboy** [comment]
> approving, though eventually Chiron will need a ring texture (or Chariklo's restored as a placeholder)

It's probably going to be Haumea's instead.

> approving, though eventually Chiron will need a ring texture (or Chariklo's restored as a placeholder)

done. Due to the asymmetry in the rings, I used the denser, wider, closer portion of the rings.

**Review by ajtribick — APPROVED** [review]

**Pull request merged**
