### PR TITLE
Update ReferenceFrames of both Cassini and Huygens

### PR DESCRIPTION
**Pull request by DaveBowman2001**
Cassini's `ReferenceFrame` is changed from `Sol` to `Sol/Saturn`, while Huygens's is changed from `Sol/Cassini` to `Sol/Saturn/Titan`. This is for the program to recognize that both spacecraft are artificial satellites of Saturn and not of the Sun. In addition, this also fixes the incorrect orientation for Huygens that was described in Issue #77 

PS. Please don't merge the two `Update galileo.ssc` commits. I don't know how to delete/exclude them from this pull request

### CODE REVIEW

**Comment by 375gnu** [comment]
please merge all commits into one

**Comment by DaveBowman2001** [comment]
How do I merge those? Actually the two other commits weren't supposed to be included in this pull request as that was my earlier (failed) attempt at changing Galileo's `ReferenceFrame`

**Comment by 375gnu** [comment]
git rebase -i master

Generally but instead of editing online I recommend using a local copy of repository and normal editor.

**Comment by SevenSpheres** [comment]
Superseded by #91

**Pull request closed without merging**
