### PR TITLE
Update star textures

### PR DESCRIPTION
**Pull request by SevenSpheres**
They now match the Blackbody D65 star colors. Most textures are by FarGetaNik (@Panterstruck) in Project Echoes. The white dwarf texture is by Frank Gregorio. Previously [Celestia#477](https://github.com/CelestiaProject/Celestia/pull/477). Closes [Celestia#113](https://github.com/CelestiaProject/Celestia/issues/113), once the corresponding PR there is merged as well. As mentioned in #4, I think having two separate repositories creates more problems than it solves...

Licenses:
- M star texture: "The images and movies found here are free for publication provided that proper credits are given." (see: https://www.su.se/isf/research/gallery/credits)
- T star texture: CC-BY-SA
- All others: Public domain

### CODE REVIEW

**Comment by SevenSpheres** [comment]
Linking [Celestia#660](https://github.com/CelestiaProject/Celestia/pull/660)

**Comment by SevenSpheres** [comment]
> why not to keep original names?

See my reply to Luke in the other PR

**Comment by 375gnu** [comment]
Another point: your `lores` textures should be `medres` while `medres` should be `hires`. And please generate real `lores` version for them (256x128).

**Comment by SevenSpheres** [comment]
This is 2020, only @Anthony-B-Russo10 has such old computers. There's no need for textures smaller than 1K IMO. Also note that @Askaniy's "lores" textures for Phobos, Deimos, and Jupiter are 1K.

**Comment by 375gnu** [comment]
3rd world people have

**Comment by pirogronian** [comment]
I dont know, what @Anthony-B-Russo10 computers are, but I have my laptop since about ten years. It has Intel Core 2 Duo and nVidia GeForce 8600GTM. But I dont know if 1k texture is too big for that hardware. Anyway, I think if there is possibility to support low-end hardware, it should be supported.

**Comment by SevenSpheres** [comment]
*sigh*...I really don't feel like doing this right now.

**Comment by Askaniy** [comment]
I understand that you need to keep the ability to launch the program’s base almost on a watch, but I can’t say in any way that 1K resolution is the maximum medium resolution (medres). If we continue to develop the old categorization (division every second power of two), I suggest renaming something like this: 
ultra-low resolution: up to **256** px
low resolution: 257-**1024** px
medium resolution: 1025-**4096** px
high resolution: 4097-**16384** px
ultra-high resolution: larger than 16k (≈64k)
_(something similar was suggested by @375gnu in September 2019)_

On the other hand, it should be checked whether the requirements for textures below 1K are really noticeable in comparison with the requirements of the program itself.

**Pull request closed without merging**
