### PR TITLE
Add lists of well known star names and dso names for localization

### PR DESCRIPTION
**Pull request by levinli303**
Generated by parsing

1. starnames.dat/galaxies.dsc/openclusters.dsc/globulars.dsc
2. https://github.com/Stellarium/stellarium/blob/master/po/stellarium-skycultures/stellarium-skycultures.pot .

Finding the ones shared in both and combined to become these lists.

### CODE REVIEW

**Comment by SevenSpheres** [comment]
I'm not sure I see the point of having these lists in `data`. If they're for translations, shouldn't they be in something like [celestia.pot](https://github.com/CelestiaProject/Celestia/blob/master/po/celestia.pot)?

**Comment by levinli303** [comment]
@SevenSpheres  celestia.pot is generated by looking at files and finding text to translate, we cannot modify it directly. here I just provided a text file for the script to generate from.

**Comment by Askaniy** [comment]
I asked ArtBlos about a list of well-known DSOs, but it's only in CO's .po file. I'll be very busy for a few more weeks, so I can't help more than copy DSO's part of it. 
[CO_DSO.txt](https://github.com/CelestiaProject/CelestiaContent/files/6576989/CO_DSO.txt)

**Review by Askaniy — APPROVED** [review]

**Comment by 375gnu** [comment]
@levinli303 why to include names from *.ssc/*.dsc files if they will be parsed anyway?

**Comment by levinli303** [comment]
@375gnu if we just parse starnames/*.dsc and put every one of them in a .pot file, then it might grow too large.

**Comment by 375gnu** [comment]
that's not a problem.

**Comment by 375gnu** [comment]
the only reason to avoid po file is to save some memory: load translation during data files loading and then unload it.

**Comment by 375gnu** [comment]
so, what's the purpose of the file now?

**Comment by levinli303** [comment]
we are not loading these files, my intention is that these files provide a filtered list of fewer translatable objects that are used to generate .po.

**Comment by 375gnu** [comment]
i'm sorry, i can't understand. you said if you add them directly into pot, it will grow too large, now you're saying that this will be used to generate pot. this is a bit confusing.

**Comment by levinli303** [comment]
i mean that if we just parse the .dsc .starnames, it will add hundreds of thousands of untranslated star/dso names to .pot file and most of them don't need to have a translation at all. So here are the curated lists used for pot generation.

**Comment by 375gnu** [comment]
okay, clear

**Review by 375gnu — APPROVED** [review]

**Pull request merged**
