### PR TITLE
Update spacecraft data & trajectories

### PR DESCRIPTION
**Pull request by SevenSpheres**
I was just going to add Beginning and Ending dates to the spacecraft missing them, but ended up updating all the spacecraft addons... Also updated Galileo model and added its probe, plus some fixes to interstellar objects. May or may not be finished, marking as draft for now. Co-author: @DaveBowman2001

### CODE REVIEW

**Review by 375gnu — CHANGES_REQUESTED** [review]
could you replace tabs with spaces

**Comment by SevenSpheres** [comment]
> could you replace tabs with spaces

This is using Celestia Origin's standard, which is also used in the Solar System data files I've updated.

**Comment by 375gnu** [comment]
> This is using Celestia Origin's standard, which is also used in the Solar System data files I've updated.

Origin is a 3rd party addon. We should not depend on 3rd party addons or their styles.

**Comment by SevenSpheres** [comment]
Nor does it say anywhere to use spaces instead of tabs. Currently, almost all data files use tabs. Is there really a good reason to change that?

**Comment by 375gnu** [comment]
The reason is to use the same style everywhere. Plz don't touch existing files but starting from this PR use only 4 spaces to indent.

**Comment by Askaniy** [comment]
I know that tabs are a sore subject, but in this case, any standard tab widths will not spoil anything. And do we really need a single standard between data files and code? If you are very insistent, then I do not mind, but so far I see no reason for this.

**Comment by SevenSpheres** [comment]
I've looked into indentation styles in the old 1.6.x data files:
Tabs - asteroids.ssc, charm2.stc, comets.ssc, extrasolar.stc, extrasolar.ssc, itokawa_locs.ssc, merc_locs.ssc, minormoons.ssc, nearstars.stc, numberedmoons.ssc, outersys.ssc, revised.stc, solarsys.ssc, hubble.ssc, apollo.ssc, shroxclassic.ssc, shroxmars.ssc, skylab.ssc
4 spaces - earth_locs.ssc, eros_locs.ssc, gaspra_locs.ssc, ida_locs.ssc, jupitermoons_locs.ssc, mars_locs.ssc, marsmoons_locs.ssc, moon_locs.ssc, neptunemoons_locs.ssc, ring_locs.ssc, saturnmoons_locs.ssc, spectbins.stc, uranusmoons_locs.ssc, venus_locs.ssc, visualbins.stc, cassini.ssc, galileo.ssc, iss.ssc, mir.ssc
8 spaces - galaxies.dsc, globulars.dsc
No indentation - world-capitals.ssc

So it looks like there was no consistent style - 4 spaces was most common for location files, tabs were most common for other files in `data`, and both were about equally common for `extras-standard` spacecraft addons. It might make sense to use 4 spaces for spacecraft and location files, but other data files such as [nearstars.stc](https://github.com/CelestiaProject/CelestiaContent/pull/72) should retain their long-standing style of using tabs.

**Comment by 375gnu** [comment]
let's do the following: if the current version uses tab then continue with tabs.

**Review by 375gnu — APPROVED** [review]

**Review by Askaniy — APPROVED** [review]

**Pull request merged**
