### PR TITLE
Resize ring textures to 1 pixel height

### LINKED ISSUE #68: Change rings textures width to 1 pixel
**Describe the bug**
This is default Saturn.
Saturn2

**To Reproduce**
1. Go to Saturn
2. Look at rings

**Expected behavior**
Rings should be rendered smoothly, like in 1.6.2 or, better, like in [this old 1.7.0 screenshot](https://celestia.space/forum/download/file.php?id=6730&filename=1.png&mode=view).

**Desktop (please complete the following information):**
 - OS: Windows
 - Frontend: Qt, native Win
 - Version: 1.7.0

**Additional context**
Possibly related or identical to [this issue](https://github.com/CelestiaProject/Celestia/issues/678) that onetwothree refused to fix. Just tested it and it's still reproducible.

### PR DESCRIPTION
**Pull request by SevenSpheres**
Closes #68. Oddly, some file sizes have increased.

### CODE REVIEW

**Review by 375gnu — APPROVED** [review]

**Comment by 375gnu** [comment]
Do you use the same compression level for resized files?

**Comment by SevenSpheres** [comment]
Looks like the textures were exported at GIMP's maximum compression level

**Comment by ajtribick** [comment]
Quick check of the PNG chunks in lores/neptune-rings.png:

Old file:
```
Chunk IHDR, length 13
Chunk bKGD, length 6
Chunk pHYs, length 9
Chunk tIME, length 7
Chunk IDAT, length 240
Chunk IEND, length 0
```

New file:
```
Chunk IHDR, length 13
Chunk zTXt, length 195
Chunk iCCP, length 389
Chunk iTXt, length 3352
Chunk bKGD, length 6
Chunk pHYs, length 9
Chunk tIME, length 7
Chunk IDAT, length 254
Chunk IEND, length 0
```

**Comment by ajtribick** [comment]
- `iTXt` contains a bunch of metadata about the GIMP version and OS used, and the timestamps.
- `zTXt` contains an EXIF chunk
- `iCCP` contains a color profile, I don't think we use this.

I think the above chunks should be removed from the files. This should be possible with pngcrush, other tools may also be able to do this.

**Review by ajtribick — CHANGES_REQUESTED** [review]
Please use pngcrush to remove unnecessary chunks.

**Comment by SevenSpheres** [comment]
Is there a Windows executable download for pngcrush? I downloaded it from SourceForge and just got C source code, and I'd rather not mess with Visual Studio if I don't have to.

**Comment by ajtribick** [comment]
If you don't have pngcrush, it looks like you can also remove these chunks by switching off various options in the GIMP's export to PNG dialog, e.g. switch off the highlighted values (the "save color values from transparent pixels" can probably be switched off also, but that would need to be on for the case of combined diffuse+specular maps, e.g. Earth)
export-dialog

**Review by ajtribick — APPROVED** [review]

**Pull request merged**
