### PR TITLE
Move data translations to content repository

### PR DESCRIPTION
**Pull request by 375gnu**
This was po2 + part of po in the main repository. See https://github.com/CelestiaProject/Celestia/pull/1193 as well.

### CODE REVIEW

**Review by Askaniy — APPROVED** [review]

**Comment by 375gnu** [comment]
@munix9 this will affect packaging

**Comment by munix9** [comment]
I see, but should not be a big problem, at least for openSUSE and AppImage. Debian stuff also needs to be customized.

**Comment by 375gnu** [comment]
@munix9 Debian files was updated as part of this PR

**Comment by munix9** [comment]
> @munix9 Debian files was updated as part of this PR

Thanks. All OBS builds have run successfully.

**Pull request merged**
